name: epiphany
adopt-info: epiphany
summary: Web browser for GNOME
description: |
  The web browser for GNOME, featuring tight integration with the desktop
  and a simple and intuitive user interface that allows you to focus on your
  web pages. If you’re looking for a simple, clean, beautiful view of the
  web, this is the browser for you.

  GNOME Web is often referred to by its code name, Epiphany.

grade: stable
confinement: strict
base: core22

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-3.0+
  title: GNOME Web

slots:
  # for GtkApplication registration
  epiphany:
    interface: dbus
    bus: session
    name: org.gnome.Epiphany

layout:
  /usr/share/epiphany:
    bind: $SNAP/usr/share/epiphany

apps:
  epiphany:
    command: bin/snapcraft-preload $SNAP/usr/bin/epiphany
    extensions: [ gnome ]
    plugs:
      - cups
      - hardware-observe
      - home
      - hostname-control
      - mount-observe
      - network
      - network-status
      - opengl
      - password-manager-service
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - upower-observe
    desktop: usr/share/applications/org.gnome.Epiphany.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      GIO_MODULE_DIR: $SNAP/snap/epiphany/current/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gio/modules/
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/epiphany

parts:
# epiphany needs access to /dev/shm/
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib

  epiphany:
    after: [snapcraft-preload]
    source: https://gitlab.gnome.org/GNOME/epiphany.git
    source-type: git
    source-tag: '42.4'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    override-build: |
      craftctl default
      sed -i 's|Icon=org.gnome.Epiphany|Icon=${SNAP}/meta/gui/org.gnome.Epiphany.svg|g' $CRAFT_PART_INSTALL/usr/share/applications/org.gnome.Epiphany.desktop
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/hicolor/scalable/apps/org.gnome.Epiphany.svg $CRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - gettext
      - itstool
      - libarchive-dev
      - libgcr-3-dev
      - libnotify-dev
      #- libsecret-1-dev
      - libsqlite3-dev
      - libwebkit2gtk-4.0-dev
      - libxml-parser-perl
      - libxml2-utils
      - libxml2-dev
      - libxslt1-dev
      - libx11-dev
      - nettle-dev
      - python3
      - python-gi-dev
      - libgirepository1.0-dev
    stage-packages:
      - gstreamer1.0-clutter-3.0
      - gstreamer1.0-gl
      - gstreamer1.0-gtk3
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-pulseaudio
      - libarchive13
      - libgcr-base-3-1
      - libgcr-ui-3-1
      - libglu1-mesa
      - libgpm2
      - libhogweed6
      - libicu70
      - libjavascriptcoregtk-4.0-18
      - libnettle8
      - libslang2
      - libsqlite3-0
      - libwebkit2gtk-4.0-37
      - libxml2
      - libxft2
    stage:
      - -usr/bin/gtk-update-icon-cache
      - -usr/lib/*/gtk-3.0/3.0.0/printbackends/libprintbackend*.so*
      - -usr/lib/*/libfribidi.so.0
      - -usr/lib/*/libatk-1.0.so.0
      - -usr/lib/*/libatk-bridge-2.0.so.0
      - -usr/lib/*/libatspi.so.0
      - -usr/lib/*/libgdk-3.so.0
      - -usr/lib/*/libgio-2.0.so*
      - -usr/lib/*/libglib-2.0.so*
      - -usr/lib/*/libgmodule-2.0.so*
      - -usr/lib/*/libgobject-2.0.so*
      - -usr/lib/*/libgthread-2.0.so*
      - -usr/lib/*/libgtk-3.so.0
      - -usr/lib/*/libgtk-3-0/gtk-query-immodules-3.0
      - -usr/lib/*/libjson-glib-1.0.so*
      - -usr/lib/*/libpango*.so*
      - -usr/lib/*/libharfbuzz*.so*
      - -usr/lib/*/libsecret-1.so.*
      - -usr/share/glib-2.0/schemas/org.gtk*
  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [epiphany]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
