name: epiphany
adopt-info: epiphany
summary: Web browser for GNOME
description: |
  The web browser for GNOME, featuring tight integration with the desktop
  and a simple and intuitive user interface that allows you to focus on your
  web pages. If you’re looking for a simple, clean, beautiful view of the
  web, this is the browser for you.

  GNOME Web is often referred to by its code name, Epiphany.

grade: stable
confinement: strict
base: core20

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-3.0+
  title: GNOME Web

slots:
  # for GtkApplication registration
  epiphany:
    interface: dbus
    bus: session
    name: org.gnome.Epiphany

apps:
  epiphany:
    command-chain: [ bin/snapcraft-preload ]
    command: usr/bin/epiphany
    extensions: [ gnome-3-38 ]
    plugs:
      - cups-control
      - hardware-observe
      - home
      - hostname-control
      - mount-observe
      - network
      - network-status
      - opengl
      - password-manager-service
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - upower-observe
    desktop: usr/share/applications/org.gnome.Epiphany.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      GIO_MODULE_DIR: $SNAP/snap/epiphany/current/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gio/modules/

parts:
# epiphany needs access to /dev/shm/
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters: [-DCMAKE_INSTALL_PREFIX=]
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib

  glib:
    source: https://gitlab.gnome.org/GNOME/glib.git
    source-branch: 'glib-2-68'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    build-environment: &buildenv
      - ACLOCAL_PATH: $SNAPCRAFT_STAGE/usr/share/aclocal
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/usr/share:$XDG_DATA_DIRS
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/vala-0.46:$LD_LIBRARY_PATH
      - GDK_PIXBUF_MODULE_FILE: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders.cache
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$PKG_CONFIG_PATH
    build-environment:
      - CFLAGS: -Wno-nonnull
    override-build: |
      set -eux
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/glib-2.0/
      cp $SNAPCRAFT_PART_INSTALL/usr/bin/{gio-querymodules,glib-compile-schemas} $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/glib-2.0/
    build-packages:
      - pkg-config
      - libmount-dev
      - gcc
      - g++
      - clang
      - libffi-dev

  json-glib:
    source: https://gitlab.gnome.org/GNOME/json-glib.git
    source-tag: '1.6.6'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dgtk_doc=disabled
      - -Dintrospection=disabled
      - -Dtests=false
    build-environment: *buildenv

  libdazzle:
    source: https://gitlab.gnome.org/GNOME/libdazzle.git
    source-depth: 1
    source-tag: 3.44.0
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Denable_gtk_doc=false
      - -Denable_tests=false
      - -Denable_tools=false
      - -Dwith_introspection=false
      - -Dwith_vapi=false
      - -Dc_args=-Wno-error=redundant-decls
    build-environment: *buildenv

  libhandy:
    source: https://gitlab.gnome.org/GNOME/libhandy.git
    source-tag: '1.4.1'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dgtk_doc=false
      - -Dtests=false
      - -Dexamples=false
      - -Dglade_catalog=disabled
      - -Dintrospection=disabled
      - -Dvapi=false
    build-environment: *buildenv

  epiphany:
    after: [snapcraft-preload, glib, json-glib, libdazzle, libhandy]
    source: https://gitlab.gnome.org/GNOME/epiphany.git
    source-type: git
    source-tag: '41.4'
    plugin: meson
    meson-parameters: [--prefix=/snap/epiphany/current/usr]
    meson-version: 0.60.3
    organize:
      snap/epiphany/current/usr: usr
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
      sed -i.bak -e 's|Icon=\s+$|Icon=${SNAP}/meta/gui/org.gnome.Epiphany.svg|g' data/org.gnome.Epiphany.desktop.in.in
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/apps/org.gnome.Epiphany.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/epiphany/current/usr/share/applications/org.gnome.Epiphany.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-environment: *buildenv
    build-packages:
      - gettext
      - itstool
      - libarchive-dev
      - libgcr-3-dev
      - libnotify-dev
      #- libsecret-1-dev
      - libsqlite3-dev
      - libwebkit2gtk-4.0-dev
      - libxml-parser-perl
      - libxml2-utils
      - libxml2-dev
      - libxslt1-dev
      - libx11-dev
      - nettle-dev
      - python3
      - python-gi-dev
      - libgirepository1.0-dev
    stage-packages:
      - gstreamer1.0-clutter-3.0
      - gstreamer1.0-gl
      - gstreamer1.0-gtk3
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-pulseaudio
      - libarchive13
      - libgcr-base-3-1
      - libgcr-ui-3-1
      - libglu1-mesa
      - libgpm2
      - libhogweed5
      - libicu66
      - libjavascriptcoregtk-4.0-18
      - libnettle7
      - libslang2
      - libsoup2.4-1
      - libsqlite3-0
      - libwebkit2gtk-4.0-37
      - libxml2
      - libxft2
    stage:
      - -usr/bin/gtk-update-icon-cache
      - -usr/lib/*/gtk-3.0/3.0.0/printbackends/libprintbackend*.so*
      - -usr/lib/*/libfribidi.so.0
      - -usr/lib/*/libatk-1.0.so.0
      - -usr/lib/*/libatk-bridge-2.0.so.0
      - -usr/lib/*/libatspi.so.0
      - -usr/lib/*/libgdk-3.so.0
      - -usr/lib/*/libgio-2.0.so*
      - -usr/lib/*/libglib-2.0.so*
      - -usr/lib/*/libgmodule-2.0.so*
      - -usr/lib/*/libgobject-2.0.so*
      - -usr/lib/*/libgthread-2.0.so*
      - -usr/lib/*/libgtk-3.so.0
      - -usr/lib/*/libgtk-3-0/gtk-query-immodules-3.0
      - -usr/lib/*/libjson-glib-1.0.so*
      - -usr/lib/*/libpango*.so*
      - -usr/lib/*/libharfbuzz*.so*
      - -usr/lib/*/libsecret-1.so.*
      - -usr/share/glib-2.0/schemas/org.gtk*
  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [epiphany]
    plugin: nil
    build-snaps: [core20, gtk-common-themes, gnome-3-38-2004]
    override-prime: |
      set -eux
      for snap in "core20" "gtk-common-themes" "gnome-3-38-2004"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
