name: epiphany
adopt-info: epiphany
summary: Web browser for GNOME
description: |
  The web browser for GNOME, featuring tight integration with the desktop
  and a simple and intuitive user interface that allows you to focus on your
  web pages. If you’re looking for a simple, clean, beautiful view of the
  web, this is the browser for you.

  GNOME Web is often referred to by its code name, Epiphany.

grade: stable
confinement: strict
base: core22

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-3.0+
  title: GNOME Web

slots:
  # for GtkApplication registration
  epiphany:
    interface: dbus
    bus: session
    name: org.gnome.Epiphany

layout:
  /usr/share/epiphany:
    bind: $SNAP/usr/share/epiphany
  /usr/lib/$CRAFT_ARCH_TRIPLET/webkitgtk-6.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/webkitgtk-6.0

apps:
  epiphany:
    command: bin/snapcraft-preload $SNAP/usr/bin/epiphany
    extensions: [ gnome ]
    plugs:
      - audio-playback
      - audio-record
      - browser-support
      - camera
      - cups
      - hardware-observe
      - home
      - hostname-control
      - mount-observe
      - network
      - network-status
      - opengl
      - password-manager-service
      - removable-media
      - screen-inhibit-control
      - upower-observe
    desktop: usr/share/applications/org.gnome.Epiphany.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas:$SNAP/gnome-platform/usr/share/glib-2.0/schemas
      GIO_MODULE_DIR: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gio/modules/
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/epiphany:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/lapack

parts:
  snapbuildtools:
    source: https://github.com/sergio-costas/snap-build-tools.git
    source-depth: 1
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-pull: |
      craftctl default
      $CRAFT_PART_SRC/install

# epiphany needs access to /dev/shm/
  snapcraft-preload:
    after: [snapbuildtools]
    source: https://github.com/sergiusens/snapcraft-preload.git
    source-depth: 1
# ext:updatesnap
#   version-format:
#     allow-neither-tag-nor-branch: true
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib

  gcr:
    source: https://gitlab.gnome.org/GNOME/gcr.git
    after: [snapbuildtools]
    source-type: git
    source-tag: '4.1.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dgtk_doc=false
      - -Dssh_agent=false
    build-packages:
      - libgpg-error-dev
    stage-packages:
      - libgpg-error0
    override-build: |
      $CRAFT_PROJECT_DIR/snapbuildtools/remove_common.py core22 gtk-common-themes gnome-42-2204
      craftctl default

  epiphany:
    after: [snapcraft-preload, gcr]
    source: https://gitlab.gnome.org/GNOME/epiphany.git
    source-type: git
    source-tag: '44.0'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     lower-than: '45'
#     no-9x-revisions: true
    plugin: meson
    parse-info: [usr/share/metainfo/org.gnome.Epiphany.appdata.xml]
    meson-parameters:
      - --prefix=/usr
    override-build: |
      $CRAFT_PROJECT_DIR/snapbuildtools/remove_common.py core22 gtk-common-themes gnome-42-2204
      craftctl default
      sed -i 's|Icon=org.gnome.Epiphany|Icon=${SNAP}/meta/gui/org.gnome.Epiphany.svg|g' $CRAFT_PART_INSTALL/usr/share/applications/org.gnome.Epiphany.desktop
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/hicolor/scalable/apps/org.gnome.Epiphany.svg $CRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - libarchive-dev
      - libxml-parser-perl
      - libxslt1-dev
      - libx11-dev
      - nettle-dev
      - python-gi-dev
      - libgirepository1.0-dev
      - gir1.2-gstreamer-1.0
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libwebkitgtk-6.0-dev
    stage-packages:
      - gstreamer1.0-clutter-3.0
      - gstreamer1.0-gl
      - gstreamer1.0-gtk3
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-pulseaudio
      - libarchive13
      - libglu1-mesa
      - libgpm2
      - libjavascriptcoregtk-4.0-18
      - libnettle8
      - libslang2
      - libsphinxbase3
      - libwebkitgtk-6.0-4
      - pulseaudio-utils

# Install all stage packages, find files provided by the base and
# platform snap and ensure they aren't duplicated in this snap
  cleanup:
    after: [epiphany]
    plugin: nil
# ext:updatesnap
#   version-format:
#     ignore: true
    override-prime: |
      set -eux
      craftctl default
      cd $CRAFT_PRIME
      rm -f usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.0
      rm -f usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.1
      mkdir -p usr/lib/$CRAFT_ARCH_TRIPLET
      ln -s ../../../gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.0 usr/lib/$CRAFT_ARCH_TRIPLET/
      ln -s ../../../gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.1 usr/lib/$CRAFT_ARCH_TRIPLET/
      cd $CRAFT_PRIME/usr/share/glib-2.0/schemas
      glib-compile-schemas .
